// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-MBA-K6g7bK5IPRVtzgSiJMWFay6n08',
    appId: '1:1049114461967:web:6122f467ab24f4fcf1a07a',
    messagingSenderId: '1049114461967',
    projectId: 'movieio-33fd8',
    authDomain: 'movieio-33fd8.firebaseapp.com',
    storageBucket: 'movieio-33fd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yRutQs-7PbDdrzo5qfqadrJ0u7vdWgI',
    appId: '1:1049114461967:android:6906b1840dc1e18bf1a07a',
    messagingSenderId: '1049114461967',
    projectId: 'movieio-33fd8',
    storageBucket: 'movieio-33fd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJ-GqP2TuyR3CigfEzVYz7ouBXBW1rIo',
    appId: '1:1049114461967:ios:0a12a0bd334595bff1a07a',
    messagingSenderId: '1049114461967',
    projectId: 'movieio-33fd8',
    storageBucket: 'movieio-33fd8.appspot.com',
    iosClientId: '1049114461967-9dad6mtvac1seunf0eg1os26snqaakq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJ-GqP2TuyR3CigfEzVYz7ouBXBW1rIo',
    appId: '1:1049114461967:ios:a8dcf794ccc3f4b5f1a07a',
    messagingSenderId: '1049114461967',
    projectId: 'movieio-33fd8',
    storageBucket: 'movieio-33fd8.appspot.com',
    iosClientId: '1049114461967-631pn4jni2oai68usqhfv00fj4g9408q.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieio.RunnerTests',
  );
}
